Jstest posix compatible ipc and  passing tests
SnrdTeam/msbuild-nodejs-redistributable pull request #5
Opened 2020-08-24 06:50 UTC by XGuppy

2020-08-24 10:09 UTC, avmorozov requested changes
Главный недостаток - запуск отдельного процесса нода для каждого тестового файла. От этого хотелось бы уйти. Вроде бы договаривались что будем стараться сделать именно так.
Пожалуйста, уничтожай мертвый код, как только его видишь. Даже если это мой код.
В целом стилистически и по понятности норм. Но есть неаккуратности со строками и бесящий меня if при запуске процессов POSIX\Windows. С последним я даже готов смириться, на бесит.

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/GenerateJasmineConfig.cs
> +        /*/// <summary>
Dead code?

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/GenerateJasmineConfig.cs
> +            //var testFiles = FindTestFilesInBuildFolder();
Dead code?

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/GenerateJasmineConfig.cs
> +            /*jsonStringBuilder.AppendLine("\t\"spec_files\": [");
Dead code

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/GenerateJasmineConfig.cs
> +            /*IEnumerable<string> FindTestFilesInBuildFolder()
Dead code

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/NPMInstallGlobal.cs
> +                executeFileName = NPMExecutable!.Split(' ')[0];
Опасносте (!) Лучший лишний чек в начале процедуры

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/NPMInstallGlobal.cs
> +                executeFileName = NPMExecutable!.Split(' ')[0];
А если не будет пробела в строке?

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/NPMInstallGlobal.cs
> +                arguments = $"{NPMExecutable.Split(' ')[1]} {CreateNPMArguments($"{packageName}@{version}")}";
OutOfBound и поминай как звали

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
> +  <Target Name="GenerateJasmineConfigAndStartup" DependsOnTargets="InstallJasmine" AfterTargets="Build">
Это же два одинаковых таргета? Зачем дублировать может объединить?

2020-08-24 10:09 UTC, avmorozov commented on src/UnitTesting/JasmineTestAdapter.cs
> +                    var jasmineResults = GetTestResultsFromJasmine(source, file);
Cильно смущает что вызовы jasmine случаются для каждого файла а не 1 раз для всех. По опыту это должно сильно удлинять дискаверинг и запуск, потому что каждый раз инициализируется виртуальная машина нода и весь жасмин парсится заново. Как правило такой запуск тестов занимает около секунды на каждый тест на средней машине. тестов вполне может быть пару десятков. Это уже 20 сек. - напряжет.

2020-08-24 10:09 UTC, avmorozov commented on src/UnitTesting/JasmineTestAdapter.cs
> +            if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
Очень не нравится мне такой if с переменным числом параметров. Очень хочется его обойти.

2020-08-24 10:09 UTC, avmorozov commented on src/UnitTesting/JasmineTestAdapter.cs
> +                result.Add(new Tuple<string, string>(clearOutputLines[i].Remove(0, 1), clearOutputLines[i + 1]));
Remove(0,1) Волшебство? А если будет ''

2020-08-24 10:09 UTC, avmorozov commented on src/UnitTesting/JasmineTestAdapter.cs
> +            foreach (var source in neededFilesWithSource.Select(fileWithSource => fileWithSource.Item1).Distinct())
Читается не очень for вместе с LINQ выражением в одной строке.

2020-08-24 10:09 UTC, avmorozov commented on src/Redistributable/Adeptik.NodeJs.Redistributable.csproj
> +	<None Include="SimpleReporter.js" Pack="True" PackagePath="" />
Точно не стоит положить в какую-нибудь папку?

2020-08-24 10:33 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +                    var jasmineResults = GetTestResultsFromJasmine(source, file);
Тогда не будем делать ссылку на исходных тестовый файл с тестами? Если не будем, то при запуске отдельного теста придётся проверять весь source, чтобы его найти. Я просто решил по такому пути пойти. Либо при каждой манипуляции с UnitTest'ами запускаем Jasmine для всего source, либо запускаем Jasmine много раз. Палка о двух концах.

2020-08-24 10:38 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +                executeFileName = NPMExecutable!.Split(' ')[0];
Пробел будет. Если Unix, то там Shell Command и аргументы. Можно было бы при определении OS, во время установки nodejs, сделать 2 выходные строки для npmexecute. Но будет обидно если есть какая-то система которая позволяет выбрать себе имя пользователя с содержанием пробельного символа.

2020-08-24 10:40 UTC, XGuppy commented on src/Redistributable/GenerateJasmineConfig.cs
> +            /*jsonStringBuilder.AppendLine("\t\"spec_files\": [");
Если говорить про единовременный запуск всех файлов на тест, то код уже не мёртвый. Об этом написал ниже.

2020-08-24 10:42 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +                result.Add(new Tuple<string, string>(clearOutputLines[i].Remove(0, 1), clearOutputLines[i + 1]));
В начале Jasmine указывает спец символ spec'а(. - окей, F - фейл) перед выводом репортера об этом spec'е. Обёртка Jasmine.

2020-08-24 10:44 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +            foreach (var source in neededFilesWithSource.Select(fileWithSource => fileWithSource.Item1).Distinct())
Вынесу LINQ.

2020-08-24 10:45 UTC, XGuppy commented on src/Redistributable/Adeptik.NodeJs.Redistributable.csproj
> +	<None Include="SimpleReporter.js" Pack="True" PackagePath="" />
Он такой одинокий... Вынесу его в папочку Reporters. Может пригодится когда-нибудь.

2020-08-24 10:53 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +            if(!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
Мне самому не очень нравится ветвление. Нужно будет подумать.

2020-08-24 10:57 UTC, avmorozov commented on src/Redistributable/NPMInstallGlobal.cs
> +                executeFileName = NPMExecutable!.Split(' ')[0];
Неясно как это гарантировать. Я бы поставил гардероб условие в начале метода.

2020-08-24 10:59 UTC, avmorozov commented on src/UnitTesting/JasmineTestAdapter.cs
> +                    var jasmineResults = GetTestResultsFromJasmine(source, file);
Мы не можем в репортере узнать имя файла в котором выполняется спек/сьют?

2020-08-24 11:00 UTC, avmorozov commented on src/UnitTesting/JasmineTestAdapter.cs
> +                result.Add(new Tuple<string, string>(clearOutputLines[i].Remove(0, 1), clearOutputLines[i + 1]));
Либо комментарий нужен, либо какое-то наименование красивое и вынос функции

2020-08-24 11:01 UTC, avmorozov commented on src/Redistributable/Adeptik.NodeJs.Redistributable.csproj
> +	<None Include="SimpleReporter.js" Pack="True" PackagePath="" />
Просто не хочется засорять Рут пакета

2020-08-24 11:16 UTC, XGuppy commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
> +  <Target Name="GenerateJasmineConfigAndStartup" DependsOnTargets="InstallJasmine" AfterTargets="Build">
С условием? В одном sh в другом cmd.

2020-08-24 11:40 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +                    var jasmineResults = GetTestResultsFromJasmine(source, file);
Никак. В структурах предоставляемых нам нет ничего чтобы дало имя файла.

2020-08-25 06:27 UTC, XGuppy commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
> +  <Target Name="GenerateJasmineConfigAndStartup" DependsOnTargets="InstallJasmine" AfterTargets="Build">
Изменил имена таргетов для лучшего понимания

2020-08-25 06:55 UTC, XGuppy commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
> +  <Target Name="GenerateJasmineConfigAndStartup" DependsOnTargets="InstallJasmine" AfterTargets="Build">
Удалил один таргет т.к. команды оболочек теперь идентичны

2020-08-30 07:24 UTC, avmorozov approved these changes

2020-08-30 07:24 UTC, avmorozov commented on src/Redistributable/GenerateJasmineConfig.cs
> +                jsonStringBuilder.AppendLine($"\t\t\t\"{testFile.Replace('\\', '/')}\"{(fileNumber++ != testFiles.Count() - 1 ? "," : "")}");
Так себе синтаксис. Не очевидный.

2020-08-30 07:24 UTC, avmorozov commented on src/Redistributable/GenerateJasmineConfig.cs
> +                return Directory.EnumerateFiles(BuildPath, $"*{JSTestExtension}", SearchOption.AllDirectories).Select(localPath => Path.GetFullPath(localPath));
Может уже перенести строки?

2020-08-30 07:24 UTC, avmorozov commented on src/Redistributable/NPMInstallGlobal.cs
> +        private static Tuple<string, string> GetExecutingFileNameAndArguments(string NPMExecutableCommand, string packageName, string packageVersion)
Tuple<string, string> -> (string executingFileName, string parameters)

2020-08-30 07:24 UTC, avmorozov commented on src/Redistributable/reporters/SimpleReporter.js
> +    //Empty
А если не определять пустые обработчики - сломается?

2020-08-30 13:04 UTC, merged