Jstest
SnrdTeam/msbuild-nodejs-redistributable pull request #8
Opened 2020-09-02 05:33 UTC by avmorozov

2020-09-02 06:18 UTC, EugeneAzhogin requested changes
Есть принципиальное несогласие
Не просмотрел ничего, связанного с jasmine

2020-09-02 06:18 UTC, EugeneAzhogin commented on src/Redistributable/InstallNodeJs.cs
> +            using var nodeInstallMutex = new Mutex(false, $@"Global\{NodeJsVersion}");
Глобальное имя для мьютекса не намекает на то, что он предназначен для Node. Если понадобится еще один мьютекс для контроля установки еще одного продукта, какой формат будет у него? (судя по логике, заложенной здесь, идентичный)

2020-09-02 06:18 UTC, EugeneAzhogin commented on src/Redistributable/InstallNodeJs.cs
> +            using var nodeInstallMutex = new Mutex(false, $@"Global\{NodeJsVersion}");
Получается, что все проекты, собираемые на одном ПК и использующие данные таск, должны использовать одну и ту же его версию, иначе поведение сборки проекта становится непредсказуемым.

2020-09-02 06:18 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +        private const string NPMCommand = "install -g";
Я считаю, глобальная установка частным проектом чего-либо недопустима. Представляете, вы запускаете сборку проекта, а он решил установить в систему свои умолчания и компоненты, после чего использование системы становится "невозможным", т.к. пользователь настраивал под себя исходя из своих субъективных предпочтений. Кроме того, если есть 2 проекта с разными версиями NPM. При этом в системе уже установлен глобально NPM определенной версии. После этого пользователь из консоли делает операции, которыми успешно до этого пользовался, и получает другой результат

2020-09-02 06:18 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +                using var NPMProcess = new Process()
зачем городить отдельный процесс?

2020-09-02 06:18 UTC, EugeneAzhogin commented on src/Redistributable/reporters/SimpleReporter.js
> +        console.log("Started\n");
В чем польза этого лога?

2020-09-02 06:18 UTC, EugeneAzhogin commented on src/Redistributable/reporters/SimpleReporter.js
> +const SimpleReporter = {
не понятно назначение reporter'а

2020-09-02 06:20 UTC, EugeneAzhogin requested changes
Есть принципиальное несогласие
Не просмотрел ничего, связанного с jasmine

2020-09-06 18:18 UTC, XGuppy commented
На **POSIX**-совместимых системах **pipe не работает** из-за различий нейминга. Возможно лучшим решением будет использование **FS PIPE** во временном хранилище? Либо совершать проверку на стороне Node'а **какая ОС используется** у пользователя?

2020-09-06 18:25 UTC, XGuppy commented
При убийстве порождённого процесса (процесс сборки), процесс командной строки с NodeJS'ом становится зомби.


### Процессы:
![Процессы](https://user-images.githubusercontent.com/33634658/92332502-685aeb80-f08f-11ea-91b4-31a3629f05d4.png)


### Убийство корневого процесса:
![Убийство корневого процесса](https://user-images.githubusercontent.com/33634658/92332503-6abd4580-f08f-11ea-8bf3-66ad9540c529.png)

### Убийство порождённого процесса:

![Убийство порожденного процесса](https://user-images.githubusercontent.com/33634658/92332504-6abd4580-f08f-11ea-86ae-44f8a5c0e6cb.png)

### Зомби:


![Зомби](https://user-images.githubusercontent.com/33634658/92332505-6b55dc00-f08f-11ea-8b52-22077364f7fb.png)

2020-09-14 06:31 UTC, EugeneAzhogin requested changes

2020-09-14 06:31 UTC, EugeneAzhogin commented on README.md
> +	"spec_files": [
Массив отформатирован не очень хорошо, что-то съехало

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/GenerateJasmineConfig.cs
> +            jsonStringBuilder.AppendLine("{");
Почему это не сделать многострочной (@) интерполированной ($) строкой?
что-то вроде:
```CSharp
var jsonString = $@"
{
   ""spec_dir"": "."
}"
```

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/InstallNodeJs.cs
> +                lockfileFilePath = Path.Combine(nodeDirectoryPath, $"{GetDistribName()}.lock");
Лучше использовать значение, сохраненное в distribName.

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +        private const int WaitingTime = 60000;
В чем измеряется время?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +            using var installPackageMutex = new Mutex(false, $@"Global\{PackageName}{PackageVersion}");
PackageVersion может быть null

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +            installPackageMutex.ReleaseMutex();
finally?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +                    if (lastSpaceIdx == -1)
Что означает проверка того, что в строке есть пробел?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +                    return (nodeExecutable, $"{npmJSRelPath} {NPMCommand} {fullPackageName}");
А нельзя ли свести к общему виду входные параметры для всех ОС, чтобы не пришлось вырезать части строки?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
>        <YarnExecutable>$(NodeExecutable) $(GlobalNodeModulesPath)/yarn/bin/yarn.js</YarnExecutable>
Судя по имени свойства - это путь к исполняемому файлу YARN, судя по значению - это команда запуска YARN. Так что это?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
> +    <WriteLinesToFile File="$(OutDir)jasmineConfig" Overwrite="true"
Зачем в файл конфигурации еще что-то дописывать? GenerateJasmineConfig не может с этим справиться?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/UnitTesting/Properties/serviceDependencies.json
> +    "secrets1": {
Где это используется?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/UnitTesting/Properties/serviceDependencies.local.json
> +    "secrets1": {
Где Это используется?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/UnitTesting/scripts/JasmineExecutor.js
> +        let spec = result.description.trim().replace(/ /g, '_').replace(/\n/g, '');
Зачем `result.description` сначала вырезается из `result.fullName`, а потом по тем же правилам обрабатывается и склеивается?

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/UnitTesting/scripts/JasmineExecutor.js
> +        let suits = result.fullName.replace(result.description, ' ').trim().replace(/ /g, '_').replace(/\n/g, '');
Переводы строк `\n` логично интерпретировать также как и пробелы, и, соответственно, заменять на `_`.

2020-09-14 06:31 UTC, EugeneAzhogin commented on src/UnitTesting/targets/build/Adeptik.NodeJs.UnitTesting.TestAdapter.props
> +    <Content Include="$(MSBuildThisFileDirectory)/../lib/netstandard2.1/Adeptik.NodeJs.UnitTesting.TestAdapter.dll">
Гарантируется, что файл будет по указанному пути?

2020-09-14 06:37 UTC, XGuppy commented on src/Redistributable/reporters/SimpleReporter.js
> +        console.log("Started\n");
Убрал сообщение, по причине использования другого средства коммуникации (пайпа)

2020-09-14 06:38 UTC, XGuppy commented on src/Redistributable/reporters/SimpleReporter.js
> +const SimpleReporter = {
Изменил нейминг репортера

2020-09-14 06:40 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +        private const string NPMCommand = "install -g";
Установка является глобальной относительно запущенного nod'а

2020-09-14 06:41 UTC, XGuppy commented on src/Redistributable/InstallNodeJs.cs
> +            using var nodeInstallMutex = new Mutex(false, $@"Global\{NodeJsVersion}");
Изменил нейминг мьютекса

2020-09-14 06:41 UTC, XGuppy commented on src/Redistributable/InstallNodeJs.cs
> +            using var nodeInstallMutex = new Mutex(false, $@"Global\{NodeJsVersion}");
Изменил нейминг мьютекса

2020-09-14 06:44 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +                using var NPMProcess = new Process()
Отдельный процесс, в отличии от задачи exec, позволяет добиться синхронизации, чтобы два и более процесса не начали установку одного пакета в одну директорию.

2020-09-14 11:37 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +            using var installPackageMutex = new Mutex(false, $@"Global\{PackageName}{PackageVersion}");
Да. Если не указывать версию в свойствах группы, то будет устанавливаться последняя версия пакета.

2020-09-14 11:41 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +            installPackageMutex.ReleaseMutex();
Мьютекст не освобождается при dispose. Исправил

2020-09-14 11:46 UTC, XGuppy commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
>        <YarnExecutable>$(NodeExecutable) $(GlobalNodeModulesPath)/yarn/bin/yarn.js</YarnExecutable>
Изменил имя на ExecuteCommandYarn

2020-09-14 11:47 UTC, XGuppy commented on src/UnitTesting/Properties/serviceDependencies.local.json
> +    "secrets1": {
Удалено. Бесполезно.

2020-09-14 11:47 UTC, XGuppy commented on src/UnitTesting/Properties/serviceDependencies.json
> +    "secrets1": {
Удалено. Бесполезно.

2020-09-14 11:52 UTC, XGuppy commented on README.md
> +	"spec_files": [
Перенёс и выровнял

2020-09-14 11:52 UTC, XGuppy commented on src/Redistributable/GenerateJasmineConfig.cs
> +            jsonStringBuilder.AppendLine("{");
Заменил

2020-09-14 11:53 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +        private const int WaitingTime = 60000;
Дополнил

2020-09-15 07:35 UTC, XGuppy commented on src/Redistributable/InstallNodeJs.cs
> +                lockfileFilePath = Path.Combine(nodeDirectoryPath, $"{GetDistribName()}.lock");
Исправил

2020-09-15 07:37 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +                    if (lastSpaceIdx == -1)
Свёл все входные параметры для процесса установки к общему виду, теперь этого кода просто нет

2020-09-15 07:37 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +                    return (nodeExecutable, $"{npmJSRelPath} {NPMCommand} {fullPackageName}");
Готово

2020-09-15 07:38 UTC, XGuppy commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
> +    <WriteLinesToFile File="$(OutDir)jasmineConfig" Overwrite="true"
Два разных файла. Переименовал файл в который записываем

2020-09-15 07:39 UTC, XGuppy commented on src/UnitTesting/scripts/JasmineExecutor.js
> +        let spec = result.description.trim().replace(/ /g, '_').replace(/\n/g, '');
Переделал

2020-09-15 07:39 UTC, XGuppy commented on src/UnitTesting/scripts/JasmineExecutor.js
> +        let suits = result.fullName.replace(result.description, ' ').trim().replace(/ /g, '_').replace(/\n/g, '');
Сделано

2020-09-15 09:28 UTC, XGuppy commented on src/UnitTesting/targets/build/Adeptik.NodeJs.UnitTesting.TestAdapter.props
> +    <Content Include="$(MSBuildThisFileDirectory)/../lib/netstandard2.1/Adeptik.NodeJs.UnitTesting.TestAdapter.dll">
Это в директории nuget-пакета. 1) Если версия .netstandard'а не будет изменена и 2) политика именования директорий у Microsoft'а не поменяются (library вместо lib), то всё будет хорошо. 1) Отметаем т.к. у нас самих не будет работать проект, а на счёт 2-ого... Тут всё возможно =)

2020-09-15 09:44 UTC, XGuppy commented on src/Redistributable/NPMInstallGlobal.cs
> +            using var installPackageMutex = new Mutex(false, $@"Global\{PackageName}{PackageVersion}");
Там же '?', что значит CanBeNull

2020-09-15 11:47 UTC, EugeneAzhogin requested changes

2020-09-15 11:47 UTC, EugeneAzhogin commented on src/Redistributable/NPMInstallGlobal.cs
> +            using var installPackageMutex = new Mutex(false, $@"Global\{PackageName}{PackageVersion}");
> Там же '?', что значит CanBeNull

Где? 
`$@"Global\{PackageName}{PackageVersion}"`

2020-09-15 11:47 UTC, EugeneAzhogin commented on src/Redistributable/targets/build/Adeptik.NodeJs.Redistributable.targets
> +    <WriteLinesToFile File="$(OutDir).execCfg.json" Overwrite="true" Lines="{&quot;NodeExecuteFile&quot;:&quot;$([MSBuild]::Escape('$(NodeExecutable.Replace('\', '\\'))'))&quot;,;&quot;JasmineLaunche
Странное использование [MSBuild]::Escape
Зачем нужен метод NodeExecutable.Replace?
https://docs.microsoft.com/ru-ru/visualstudio/msbuild/property-functions?view=vs-2019

2020-09-17 10:49 UTC, EugeneAzhogin requested changes

2020-09-17 10:49 UTC, EugeneAzhogin commented on src/UnitTesting/JasmineTestAdapter.cs
> +        private const string PathToProjectRootFromBin = "../../../";
Путь папки "bin" может меняться и рассчитывать, что ProjectRoot будет на 3 уровня выше, нельзя.

2020-09-17 10:49 UTC, EugeneAzhogin commented on src/UnitTesting/JasmineTestAdapter.cs
> +                        while (true)
А нельзя просто дождаться конца потока readerPipe?

2020-09-17 10:49 UTC, EugeneAzhogin commented on src/UnitTesting/JasmineTestAdapter.cs
> +                            if (String.IsNullOrWhiteSpace(lineFromPipe))
Странно пустую строку считать концом потока

2020-09-17 10:49 UTC, EugeneAzhogin commented on src/UnitTesting/scripts/JasmineExecutor.js
> +        result.fullName = result.fullName.replaceAt(result.fullName.indexOf(result.description) - 1, '.').replace(/\s+/g, '_');
Если `result.fullName.indexOf(result.description)` окажется `-1`, то замена произойдет в позиции 2

2020-09-17 11:11 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +                        while (true)
Пакет FIN не сработал при работе в POSIX системе

2020-09-17 11:11 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +        private const string PathToProjectRootFromBin = "../../../";
Добавил в LaunchSettings путь до проектной директории

2020-09-17 11:12 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +                            if (String.IsNullOrWhiteSpace(lineFromPipe))
Можно на null. Поменять т.к. после fin в posix из пайпа сыпятся null'ы (Что и должно значить завершение)

2020-09-17 11:14 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +                            if (String.IsNullOrWhiteSpace(lineFromPipe))
Поменял

2020-09-17 11:15 UTC, XGuppy commented on src/UnitTesting/JasmineTestAdapter.cs
> +                        while (true)
Точнее сработал не так как от него ожидалось. Он не изменил флаг доступности пайпа.

2020-09-17 11:18 UTC, XGuppy commented on src/UnitTesting/scripts/JasmineExecutor.js
> +        result.fullName = result.fullName.replaceAt(result.fullName.indexOf(result.description) - 1, '.').replace(/\s+/g, '_');
Если мы попали в данным метод, то spec существует. Как может получиться `-1`?

2020-09-18 06:35 UTC, EugeneAzhogin requested changes
Комментарии к README.md

2020-09-18 06:35 UTC, EugeneAzhogin commented on README.md
>  MSBuild targets for:
Не все гиперссылки работают

2020-09-18 06:35 UTC, EugeneAzhogin commented on README.md
> +Target `GenerateJasmineConfigAndStartup` will generate configuration file (`jasmine.json`) and file which contains launch settings of jasmine (jasmine launcher file [`JasmineExecutor.js`](./src/UnitT
GenerateJasmineConfigAndStartup теперь по-другому называется

2020-09-18 06:35 UTC, EugeneAzhogin commented on README.md
>      <YarnBuildCommand>build</YarnBuildCommand>
Версию YARN указывать не надо?

2020-09-18 06:35 UTC, EugeneAzhogin commented on README.md
> +* All test case output files must adhere to the following name format `nameOfYourTestFile.test.js`.
Не очень понятно где обязательная часть имени файла, а где переменная

2020-09-18 07:38 UTC, XGuppy commented on README.md
>  MSBuild targets for:
Исправил

2020-09-18 07:38 UTC, XGuppy commented on README.md
> +Target `GenerateJasmineConfigAndStartup` will generate configuration file (`jasmine.json`) and file which contains launch settings of jasmine (jasmine launcher file [`JasmineExecutor.js`](./src/UnitT
Пока нет. Это наименование секции. Но я переименую

2020-09-18 08:24 UTC, XGuppy commented on README.md
> +* All test case output files must adhere to the following name format `nameOfYourTestFile.test.js`.
Немного уточнил

2020-09-18 08:36 UTC, XGuppy commented on README.md
>      <YarnBuildCommand>build</YarnBuildCommand>
Как указывать версию YARN'а указано в описании таргета "Yarn installation"

2020-09-18 13:03 UTC, EugeneAzhogin approved these changes

2020-09-18 13:17 UTC, merged